import { Inter, Cedarville_Cursive, Montserrat } from "next/font/google";
import "./globals.css";

const cursive = Cedarville_Cursive({ subsets: ["latin"] , weight : "400"});
const inter = Inter({ subsets: ["latin"] , weight : "400"});
const monteserrat = Montserrat({ subsets: ["latin"] , weight : "400"});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={monteserrat.className}
        style={{ background: "url(/bg.jpg)", backgroundSize: "Cover" }}
      >
        {children}
      </body>
    </html>
  );
}
